# Generated by Django 3.1.7 on 2021-04-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0002_auto_20210410_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="slug",
            field=models.SlugField(allow_unicode=True, default="---"),
            preserve_default=False,
        ),
    ]
