# Generated by Django 3.1.7 on 2021-04-22 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qa", "0006_auto_20210420_1753"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questionvote",
            unique_together={("user", "question")},
        ),
    ]
