# Generated by Django 3.1.7 on 2021-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0008_auto_20210509_1737"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ("-vote",)},
        ),
        migrations.AddField(
            model_name="answer",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="answer",
            name="accepted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
