# Generated by Django 3.1.7 on 2021-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0009_auto_20210524_1823"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
