# Generated by Django 3.1.8 on 2021-06-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0011_auto_20210607_1938"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
