# Generated by Django 3.1.9 on 2021-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0012_question_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="content_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
