# Generated by Django 3.1.7 on 2021-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.IntegerField(default=1),
        ),
    ]
