# Generated by Django 3.1.7 on 2021-05-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_reputationhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_me",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="title",
            field=models.CharField(default="", max_length=400),
        ),
    ]
